'use client';

import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, BatteryCharging, Boxes, Car, Database, Lightbulb, LockKeyhole, Moon, QrCode, Radio, Shirt, Sun, Wrench } from 'lucide-react';

const passportData = [
  ['Produktidentitet','Modell, batch eller unik produkt'],
  ['Material & innehåll','Komposition, återvunnet innehåll och ämnen'],
  ['Livscykel','Tillverkning, service, reparation och återvinning'],
  ['Dokumentation','Manualer, certifikat, garanti och reservdelar']
];

const connections = [
  {icon:Lightbulb,title:'Lampor & armaturer',text:'Produktdata, energiinformation, installation och servicehistorik följer varje enhet.'},
  {icon:LockKeyhole,title:'Lås & access',text:'Koppla identitet, behörig dokumentation, garanti och felanmälan till rätt produkt.'},
  {icon:Radio,title:'Sensorer & IoT',text:'Låt sensordata och status uppdatera produktens digitala livscykel i realtid.'},
  {icon:Wrench,title:'Maskiner & service',text:'Rätt reservdel, instruktion och serviceärende blir tillgängligt direkt vid produkten.'},
  {icon:Database,title:'ERP, PIM & CRM',text:'Blippa kan bli det sammanhållande lagret mellan befintliga system och användaren.'},
  {icon:Boxes,title:'Cirkulära flöden',text:'Stöd återbruk, ägarbyte, rekonditionering och återvinning med verifierbar historik.'}
];

export default function DppPage(){
  const [theme,setTheme]=useState<'dark'|'light'>('dark');
  useEffect(()=>{const saved=localStorage.getItem('selectec-theme');const next=saved==='light'?'light':'dark';setTheme(next);document.documentElement.dataset.theme=next;const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('[data-reveal]').forEach(element=>observer.observe(element));return()=>observer.disconnect()},[]);
  useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('selectec-theme',theme)},[theme]);
  return <main className="dpp-page">
    <header className="dpp-header"><a className="brand" href="/"><img src="/selectec-nordic-logo-hq.png" alt="Selectec Nordic"/></a><nav aria-label="DPP meny"><a href="#vad">Vad är DPP?</a><a href="#regelverk">Regelverk</a><a href="#blippa">Blippa</a><a href="#iot">IoT</a></nav><div><button className="theme-toggle" onClick={()=>setTheme(theme==='dark'?'light':'dark')} aria-label={theme==='dark'?'Aktivera ljust tema':'Aktivera mörkt tema'}>{theme==='dark'?<Sun size={16}/>:<Moon size={16}/>}</button><a className="dpp-back" href="/"><ArrowLeft size={15}/> Till Selectec</a></div></header>

    <section className="dpp-hero" id="vad"><div className="dpp-grid"/><div className="dpp-hero-copy"><span className="dpp-kicker">DPP / DIGITALT PRODUKTPASS</span><h1>Varje produkt får<br/><strong>ett digitalt liv.</strong></h1><p>En enkel QR-kod på produkten öppnar rätt information direkt i mobilen. Kunden kan se innehåll och skötsel, en tekniker kan hitta serviceinformation och ni kan uppdatera allt utan att byta etiketten.</p><div className="dpp-hero-actions"><a className="primary-button" href="#exempel">Se två konkreta exempel <ArrowRight size={17}/></a><a className="text-link" href="#regelverk">Förstå regelverket <span>↓</span></a></div></div><div className="passport-orbit" aria-label="En QR-kod som öppnar produktens digitala information"><div className="passport-ring ring-one"/><div className="passport-ring ring-two"/><div className="passport-core"><QrCode/></div>{['MATERIAL','SERVICE','ORIGIN','CIRCULARITY'].map((label,index)=><span key={label} className={`passport-node passport-node-${index+1}`}>{label}</span>)}</div></section>

    <section className="dpp-definition" data-reveal><div><span className="section-index">01 / EN DIGITAL TVILLING</span><h2>En skanning.<br/>Hela berättelsen.</h2></div><div className="passport-data-grid">{passportData.map(([title,text],index)=><article key={title}><span>0{index+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>

    <section className="plain-examples" id="exempel"><div className="plain-examples-intro" data-reveal><span className="section-index">SÅ KAN DET FUNGERA</span><h2>Två företag.<br/>Två enkla vinster.</h2><p>Man behöver inte kunna något om IoT, databärare eller EU-standarder för att komma igång. Vi börjar med vad ni vill att kunden eller produkten ska kunna göra.</p></div><div className="plain-example-grid"><article data-reveal><Shirt/><span>KLÄDTILLVERKAREN</span><h3>Från fiber till färdig jacka</h3><p>En tillverkare i Norrland sätter en QR-kod på plagget. Kunden ser material, ursprung, tvättråd och reparationshjälp. Tillverkaren uppdaterar informationen centralt och står bättre förberedd när DPP-kraven för textil blir konkreta.</p><b>Resultat: enklare information, starkare transparens och en väg mot reparation eller återbruk.</b></article><article data-reveal><Car/><span>BILREKONDAREN</span><h3>Från engångsjobb till nästa besök</h3><p>Efter rekonden sätter företaget en diskret QR-dekal i bilen. Bilägaren kan se utförda behandlingar, skötselråd och boka nästa tvätt, lackskydd eller invändig behandling med ett tryck.</p><b>Resultat: fler återbesök och relevant merförsäljning utan en egen app.</b><small>Detta är en Blippa-kundupplevelse — inte ett lagstadgat digitalt produktpass.</small></article></div></section>

    <section className="dpp-proof" id="blippa"><div className="dpp-proof-image" data-reveal><img src="/dpp/fashion-passport.jpg" alt="Exempel på Blippa-produktpass för ett klädesplagg"/><span>EXEMPEL / MODE & TEXTIL</span></div><div className="dpp-proof-copy" data-reveal><span className="section-index">02 / BLIPPA</span><h2>Från compliance till konkurrensfördel.</h2><p>Blippa skapar en personlig digital yta för varje produkt. Samma ingång kan visa rätt information för konsumenten, serviceteknikern, återförsäljaren eller återvinnaren — på rätt språk och med rätt behörighet.</p><ul><li><b>Publicera utan friktion.</b> Produktinformation, dokument och media kan uppdateras efter att produkten lämnat fabriken.</li><li><b>Bygg relationen vidare.</b> Registrering, garanti, guider, reservdelar, erbjudanden och support samlas på samma plats.</li><li><b>Spåra livscykeln.</b> Händelser från produktion till återbruk skapar en historia som går att följa och använda.</li></ul></div></section>

    <section className="dpp-law" id="regelverk"><div className="law-intro" data-reveal><span className="section-index">03 / EU-REGELVERK</span><h2>Förbered nu.<br/>Införandet sker stegvis.</h2><p>EU:s ekodesignförordning ESPR är ramverket för digitala produktpass. De exakta informationskraven och datumen beslutas produktgrupp för produktgrupp genom delegerade akter. Det finns alltså inte ett enda startdatum för alla produkter.</p></div><div className="law-timeline" data-reveal><article className="law-now"><span>2024</span><h3>ESPR träder i kraft</h3><p>Förordning (EU) 2024/1781 etablerar ramverket. Passet ska bland annat vara kopplat till en unik produktidentifierare, bygga på öppna standarder och vara tillgängligt under produktens förväntade livslängd.</p></article><article className="law-battery"><BatteryCharging/><span>18 FEB 2027</span><h3>Batteripasset blir konkret</h3><p>Batteripass krävs för batterier till lätta transportmedel, industribatterier över 2 kWh och elfordonsbatterier som släpps på EU-marknaden.</p></article><article><span>2025–2030</span><h3>Prioriterade produktgrupper</h3><p>EU:s arbetsplan prioriterar bland annat textil/kläder, möbler, däck, madrasser, järn och stål samt aluminium. Kraven utvecklas stegvis och blir produktspecifika.</p></article></div><div className="law-note"><b>Viktigt:</b> Detta är en översikt, inte juridisk rådgivning. Tillämpning och tidplan behöver alltid bedömas för er produktgrupp.<div><a href="https://eur-lex.europa.eu/eli/reg/2024/1781/oj" target="_blank" rel="noreferrer">ESPR på EUR-Lex ↗</a><a href="https://eur-lex.europa.eu/eli/reg/2023/1542/oj" target="_blank" rel="noreferrer">Batteriförordningen ↗</a><a href="https://environment.ec.europa.eu/news/sustainable-products-be-norm-consumers-new-regulation-2024-07-19_en" target="_blank" rel="noreferrer">EU-kommissionens översikt ↗</a></div></div></section>

    <section className="dpp-iot" id="iot"><div className="iot-heading" data-reveal><span className="section-index">04 / BEYOND THE PASSPORT</span><h2>Blippa möter<br/><strong>den uppkopplade produkten.</strong></h2><p>När produktpasset kopplas till fysisk identitet, sensordata och affärssystem uppstår en gemensam digital nerv för hela produktens liv.</p></div><div className="connection-grid">{connections.map(({icon:Icon,title,text},index)=><article key={title} data-reveal style={{'--delay':`${index%3*80}ms`} as React.CSSProperties}><Icon/><span>0{index+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>

    <section className="connected-demo"><div className="connected-demo-copy" data-reveal><span className="section-index">05 / SERVICE I PRODUKTEN</span><h2>Skanna. Förstå. Agera.</h2><p>I samma upplevelse kan användaren se produktdata, få AI-stöd, starta en felanmälan och lämna information vidare till rätt serviceflöde. För en lampa kan det vara installation och energidata. För ett lås kan det vara behörig service. För en maskin kan det vara reservdelar och realtidsstatus.</p><a className="primary-button" href="mailto:info@selectecnordic.com?subject=DPP%20och%20Blippa">Utforska ett Blippa-case <ArrowRight size={17}/></a></div><div className="connected-demo-image" data-reveal><img src="/dpp/connected-service.jpg" alt="Exempel på Blippa som digital serviceyta för en uppkopplad produkt"/><span>EXEMPEL / SERVICE & UPPKOPPLING</span></div></section>

    <section className="dpp-cta"><QrCode/><span>FRÅN FÖRSTA PRODUKTDATA TILL LEVANDE PRODUKTPASS</span><h2>Vilken produkt vill ni<br/>göra digital först?</h2><a href="mailto:info@selectecnordic.com?subject=Vi%20vill%20prata%20DPP">Boka en DPP-workshop <ArrowRight/></a></section>
    <footer><a className="brand footer-brand" href="/"><img src="/selectec-nordic-logo-hq.png" alt="Selectec Nordic"/></a><p>Digitala produktpass, uppkopplade produkter och nordisk implementation.</p><div><a href="/">Selectec Nordic</a><a href="https://blippa.com/sv/produkt/" target="_blank" rel="noreferrer">Blippa</a></div><small>© 2026 Selectec Nordic</small></footer>
  </main>
}
