'use client';

import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, BatteryCharging, Boxes, Car, Database, Lightbulb, LockKeyhole, MessageCircle, Moon, QrCode, Radio, Shirt, Sun, Wrench } from 'lucide-react';

const passportData = [
  ['Produktidentitet','Modell, batch eller unik produkt'],
  ['Material & innehåll','Komposition, återvunnet innehåll och ämnen'],
  ['Livscykel','Tillverkning, service, reparation och återvinning'],
  ['Dokumentation','Manualer, certifikat, garanti och reservdelar']
];

const connections = [
  {icon:Lightbulb,title:'Lampor & armaturer',text:'Produktdata, energiinformation, installation och servicehistorik följer varje enhet.'},
  {icon:LockKeyhole,title:'Lås & access',text:'Koppla identitet, behörig dokumentation, garanti och felanmälan till rätt produkt.'},
  {icon:Radio,title:'Sensorer & IoT',text:'Låt sensordata och status uppdatera produktens digitala livscykel i realtid.'},
  {icon:Wrench,title:'Maskiner & service',text:'Rätt reservdel, instruktion och serviceärende blir tillgängligt direkt vid produkten.'},
  {icon:Database,title:'ERP, PIM & CRM',text:'Blippa kan bli det sammanhållande lagret mellan befintliga system och användaren.'},
  {icon:Boxes,title:'Cirkulära flöden',text:'Stöd återbruk, ägarbyte, rekonditionering och återvinning med verifierbar historik.'}
];

const builderOptions = ['Support','Skötselråd','Manual','AI-assistent','Felanmälan','Koppla CRM','Koppla ERP'];

export default function DppPage(){
  const [theme,setTheme]=useState<'dark'|'light'>('dark');
  const [demoProduct,setDemoProduct]=useState('Nordic Pro 3000');
  const [demoModel,setDemoModel]=useState('NP-3000');
  const [demoSerial,setDemoSerial]=useState('SE-2026-0142');
  const [demoButtons,setDemoButtons]=useState(['Support','Manual','AI-assistent']);
  useEffect(()=>{const saved=localStorage.getItem('selectec-theme');const next=saved==='light'?'light':'dark';setTheme(next);document.documentElement.dataset.theme=next;const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('[data-reveal]').forEach(element=>observer.observe(element));return()=>observer.disconnect()},[]);
  useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('selectec-theme',theme)},[theme]);
  return <main className="dpp-page">
    <header className="dpp-header"><a className="brand" href="/"><img className="logo-color" src="/selectec-nordic-logo-hq.png" alt="Selectec Nordic"/><img className="logo-mono" src="/selectec-nordic-logo-mono.png" alt="" aria-hidden="true"/></a><nav aria-label="DPP meny"><a href="#vad">Vad är DPP?</a><a href="#regelverk">Regelverk</a><a href="#blippa">Blippa</a><a href="#iot">IoT</a></nav><div><button className="theme-toggle" onClick={()=>setTheme(theme==='dark'?'light':'dark')} aria-label={theme==='dark'?'Aktivera ljust tema':'Aktivera mörkt tema'}>{theme==='dark'?<Sun size={16}/>:<Moon size={16}/>}</button><a className="dpp-back" href="/"><ArrowLeft size={15}/> Till Selectec</a></div></header>

    <section className="dpp-hero" id="vad"><div className="dpp-grid"/><div className="dpp-hero-copy"><span className="dpp-kicker">DPP / DIGITALT PRODUKTPASS</span><h1>En QR-kod.<br/><strong>Rätt information direkt.</strong></h1><p>Sätt en QR-kod på plagget, maskinen eller bilen. Den som skannar kan få produktinformation, skötselråd, service, support eller ett erbjudande – utan att installera en app.</p><div className="dpp-hero-actions"><a className="primary-button" href="#exempel">Se tre konkreta exempel <ArrowRight size={17}/></a><a className="text-link" href="#regelverk">Vad kräver lagen? <span>↓</span></a></div></div><div className="passport-orbit" aria-label="En QR-kod som öppnar produktens digitala information"><div className="passport-ring ring-one"/><div className="passport-ring ring-two"/><div className="passport-core"><QrCode/></div>{['INNEHÅLL','SKÖTSEL','SERVICE','ÅTERBRUK'].map((label,index)=><span key={label} className={`passport-node passport-node-${index+1}`}>{label}</span>)}</div></section>

    <section className="plain-examples" id="exempel"><div className="plain-examples-intro" data-reveal><span className="section-index">SÅ KAN DET FUNGERA</span><h2>Tre QR-koder.<br/>Tre olika upplevelser.</h2><p>Blippa behöver inte se likadant ut för alla. Varje sida kan få kundens färger, innehåll och funktioner – från en enkel produktsida till support med en digital assistent.</p></div><div className="plain-example-grid"><article data-reveal><Shirt/><span>KLÄDTILLVERKAREN</span><h3>Vad består jackan av?</h3><p>Kunden skannar etiketten och ser material, ursprung, tvättråd och hur plagget kan repareras eller lämnas till återbruk.</p><b>Nytta: tydlig produktinformation och en praktisk väg mot kommande DPP-krav.</b></article><article data-reveal><Car/><span>BILREKONDAREN</span><h3>När är nästa behandling?</h3><p>En diskret QR-dekal i bilen visar vad som gjorts, skötselråd och en knapp för att boka nästa tvätt, lackskydd eller invändig behandling.</p><b>Nytta: fler återbesök och relevant merförsäljning utan en egen app.</b><small>Detta är en digital kundupplevelse, inte ett lagstadgat produktpass.</small></article><article data-reveal><MessageCircle/><span>MASKINEN HOS KUNDEN</span><h3>Hur löser jag problemet?</h3><p>Teknikern skannar maskinen och får rätt manual, reservdelar och felsökning. En digital assistent kan svara utifrån just den produktens information och hjälpa till att skapa ett serviceärende.</p><b>Nytta: snabbare hjälp och färre samtal där ingen vet exakt vilken modell kunden har.</b></article></div></section>

    <section className="blippa-showcase" data-reveal><div className="showcase-heading"><span className="section-index">RIKTIGA EXEMPEL FRÅN BLIPPA</span><h2>Samma plattform.<br/>Helt olika sidor.</h2><p>Mode, laddplatser och uthyrningsutrustning visar hur varje QR-sida kan anpassas efter produkten, varumärket och användarens nästa steg.</p></div><div className="showcase-grid"><a href="https://blippa.com/sv/discover/mode/" target="_blank" rel="noreferrer"><div><img src="/dpp/examples/fashion-pass.png" alt="Haglöfs QR-exempel skapat i Blippa"/></div><span>MODE & DPP</span><b>Produktinformation direkt i plagget ↗</b></a><a href="https://blippa.com/sv/discover/laddplatser/" target="_blank" rel="noreferrer"><div><img src="/dpp/examples/charging-screen.png" alt="Blippa-sida för en laddplats"/></div><span>LADDPLATS</span><b>Information och bokning på plats ↗</b></a><a href="https://blippa.com/sv/discover/uthyrning-av-utrustning/" target="_blank" rel="noreferrer"><div><img src="/dpp/examples/rental.png" alt="Blippa-sida för hyrd utrustning"/></div><span>UTHYRNINGSUTRUSTNING</span><b>Rätt maskindata för rätt exemplar ↗</b></a></div></section>

    <section className="blippa-builder" data-reveal><div className="builder-intro"><span className="section-index">PROVA PRINCIPEN / SIMULERING</span><h2>Bygg en enkel<br/>QR-sida på en minut.</h2><p>Använd Blippas No-code-plattform för att bygga unika QR-webbplatser på några få minuter. De fungerar på alla mobila enheter. Ingen app eller kodkunskap krävs.</p><div className="standard-note"><QrCode/><div><b>GS1 Digital Link</b><span>Blippa har stöd för standardiserade produktlänkar med exempelvis GTIN, batch och serienummer.</span></div></div></div><div className="builder-workspace"><div className="builder-controls"><label>Produktnamn<input value={demoProduct} onChange={event=>setDemoProduct(event.target.value)} maxLength={30}/></label><label>Modell<input value={demoModel} onChange={event=>setDemoModel(event.target.value)} maxLength={24}/></label><label>Serienummer<input value={demoSerial} onChange={event=>setDemoSerial(event.target.value)} maxLength={24}/></label><fieldset><legend>Lägg till knappar</legend><div>{builderOptions.map(option=><button key={option} className={demoButtons.includes(option)?'active':''} onClick={()=>setDemoButtons(current=>current.includes(option)?current.filter(item=>item!==option):[...current,option])}>{demoButtons.includes(option)?'✓':'+'} {option}</button>)}</div></fieldset><small>Detta är en förenklad demonstration, inte Blippas riktiga editor.</small></div><div className="builder-phone"><div className="phone-bar"><span/><span/><span/></div><div className="phone-brand">ER LOGOTYP</div><div className="phone-product"><QrCode/><small>PRODUKTSIDA</small><h3>{demoProduct||'Produktnamn'}</h3><dl><div><dt>Modell</dt><dd>{demoModel||'–'}</dd></div><div><dt>Serienummer</dt><dd>{demoSerial||'–'}</dd></div></dl>{demoButtons.map(option=><button key={option}>{option==='AI-assistent'?<MessageCircle size={16}/>:<ArrowRight size={15}/>} {option}</button>)}</div><div className="phone-gs1">GS1 DIGITAL LINK · DEMO</div></div></div></section>

    <section className="dpp-definition" data-reveal><div><span className="section-index">01 / VAD KAN SIDAN VISA?</span><h2>En skanning.<br/>Det man behöver veta.</h2></div><div className="passport-data-grid">{passportData.map(([title,text],index)=><article key={title}><span>0{index+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>

    <section className="dpp-proof" id="blippa"><div className="dpp-proof-image" data-reveal><img src="/dpp/fashion-passport.jpg" alt="Exempel på Blippa-produktpass för ett klädesplagg"/><span>EXEMPEL / MODE & TEXTIL</span></div><div className="dpp-proof-copy" data-reveal><span className="section-index">02 / BLIPPA</span><h2>En sida för varje produkt.</h2><p>Blippa kopplar en QR-kod till en sida som ni själva kan uppdatera. Kunden kan se en sak, serviceteknikern en annan. Sidan kan följa ert varumärke och visas på flera språk.</p><ul><li><b>Ändra innehållet i efterhand.</b> Uppdatera manualer, bilder och information utan att byta QR-koden.</li><li><b>Lägg till en AI-assistent.</b> Låt användaren ställa frågor och få svar utifrån informationen för just den produkten.</li><li><b>Samla nästa steg.</b> Garanti, guider, reservdelar, erbjudanden och support finns på samma sida.</li><li><b>Följ produktens historia.</b> Lägg till service, ägarbyten, reparationer och återbruk när det behövs.</li></ul></div></section>

    <section className="dpp-law" id="regelverk"><div className="law-intro" data-reveal><span className="section-index">03 / EU-REGELVERK</span><h2>Förbered nu.<br/>Införandet sker stegvis.</h2><p>EU:s ekodesignförordning ESPR är ramverket för digitala produktpass. De exakta informationskraven och datumen beslutas produktgrupp för produktgrupp genom delegerade akter. Det finns alltså inte ett enda startdatum för alla produkter.</p></div><div className="law-timeline" data-reveal><article className="law-now"><span>2024</span><h3>ESPR träder i kraft</h3><p>Förordning (EU) 2024/1781 etablerar ramverket. Passet ska bland annat vara kopplat till en unik produktidentifierare, bygga på öppna standarder och vara tillgängligt under produktens förväntade livslängd.</p></article><article className="law-battery"><BatteryCharging/><span>18 FEB 2027</span><h3>Batteripasset blir konkret</h3><p>Batteripass krävs för batterier till lätta transportmedel, industribatterier över 2 kWh och elfordonsbatterier som släpps på EU-marknaden.</p></article><article><span>2025–2030</span><h3>Prioriterade produktgrupper</h3><p>EU:s arbetsplan prioriterar bland annat textil/kläder, möbler, däck, madrasser, järn och stål samt aluminium. Kraven utvecklas stegvis och blir produktspecifika.</p></article></div><div className="law-note"><b>Viktigt:</b> Detta är en översikt, inte juridisk rådgivning. Tillämpning och tidplan behöver alltid bedömas för er produktgrupp.<div><a href="https://eur-lex.europa.eu/eli/reg/2024/1781/oj" target="_blank" rel="noreferrer">ESPR på EUR-Lex ↗</a><a href="https://eur-lex.europa.eu/eli/reg/2023/1542/oj" target="_blank" rel="noreferrer">Batteriförordningen ↗</a><a href="https://environment.ec.europa.eu/news/sustainable-products-be-norm-consumers-new-regulation-2024-07-19_en" target="_blank" rel="noreferrer">EU-kommissionens översikt ↗</a></div></div></section>

    <section className="dpp-iot" id="iot"><div className="iot-heading" data-reveal><span className="section-index">04 / MER ÄN INFORMATION</span><h2>När produkten också<br/><strong>kan skicka och ta emot.</strong></h2><p>Blippa kan kopplas till de system ni redan använder. Då kan en skanning exempelvis öppna ett lås för rätt person, visa aktuell maskinstatus eller skapa ett serviceärende med rätt produktnummer.</p></div><div className="connection-grid">{connections.map(({icon:Icon,title,text},index)=><article key={title} data-reveal style={{'--delay':`${index%3*80}ms`} as React.CSSProperties}><Icon/><span>0{index+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>

    <section className="connected-demo"><div className="connected-demo-copy" data-reveal><span className="section-index">05 / SERVICE I PRODUKTEN</span><h2>Skanna. Förstå. Agera.</h2><p>I samma upplevelse kan användaren se produktdata, få AI-stöd, starta en felanmälan och lämna information vidare till rätt serviceflöde. För en lampa kan det vara installation och energidata. För ett lås kan det vara behörig service. För en maskin kan det vara reservdelar och realtidsstatus.</p><a className="primary-button" href="mailto:info@selectecnordic.com?subject=DPP%20och%20Blippa">Utforska ett Blippa-case <ArrowRight size={17}/></a></div><div className="connected-demo-image" data-reveal><img src="/dpp/connected-service.jpg" alt="Exempel på Blippa som digital serviceyta för en uppkopplad produkt"/><span>EXEMPEL / SERVICE & UPPKOPPLING</span></div></section>

    <section className="dpp-cta"><QrCode/><span>FRÅN FÖRSTA PRODUKTDATA TILL LEVANDE PRODUKTPASS</span><h2>Vilken produkt vill ni<br/>göra digital först?</h2><a href="mailto:info@selectecnordic.com?subject=Vi%20vill%20prata%20DPP">Boka en DPP-workshop <ArrowRight/></a></section>
    <footer><a className="brand footer-brand" href="/"><img src="/selectec-nordic-logo-mono.png" alt="Selectec Nordic"/></a><p>Digitala produktpass, uppkopplade produkter och nordisk implementation.</p><div><a href="/">Selectec Nordic</a><a href="https://blippa.com/sv/produkt/" target="_blank" rel="noreferrer">Blippa</a></div><small>© 2026 Selectec Nordic</small></footer>
  </main>
}
