'use client';

import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, BarChart3, Check, Cloud, Leaf, LockKeyhole, Moon, Printer, Server, ShieldCheck, Sun, Users } from 'lucide-react';

const benefits=[
  {icon:LockKeyhole,title:'Säkra dokumenten',text:'Användaren identifierar sig vid skrivaren innan dokumentet lämnar enheten.'},
  {icon:BarChart3,title:'Se och styr kostnaden',text:'Följ utskrifter per användare, avdelning och enhet. Sätt regler där de gör nytta.'},
  {icon:Printer,title:'Fungerar med blandade miljöer',text:'Behåll valfriheten när organisationen använder skrivare från flera tillverkare.'},
  {icon:Leaf,title:'Minska onödiga utskrifter',text:'Find-Me-utskrift, kvoter och tydlig uppföljning hjälper er minska svinnet.'}
];

export default function PaperCutPage(){
  const [theme,setTheme]=useState<'dark'|'light'>('dark');
  useEffect(()=>{const saved=localStorage.getItem('selectec-theme');const next=saved==='light'?'light':'dark';setTheme(next);document.documentElement.dataset.theme=next;const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('[data-reveal]').forEach(element=>observer.observe(element));return()=>observer.disconnect()},[]);
  useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('selectec-theme',theme)},[theme]);
  return <main className="papercut-page">
    <header className="dpp-header"><a className="brand" href="/"><img className="logo-color" src="/selectec-nordic-logo-hq.png" alt="Selectec Nordic"/><img className="logo-mono" src="/selectec-nordic-logo-mono.png" alt="" aria-hidden="true"/></a><nav aria-label="PaperCut meny"><a href="#varfor">Varför PaperCut?</a><a href="#valj">MF eller Hive</a><a href="#selectec">Selectec</a></nav><div><button className="theme-toggle" onClick={()=>setTheme(theme==='dark'?'light':'dark')} aria-label={theme==='dark'?'Aktivera ljust tema':'Aktivera mörkt tema'}>{theme==='dark'?<Sun size={16}/>:<Moon size={16}/>}</button><a className="dpp-back" href="/"><ArrowLeft size={15}/> Till Selectec</a></div></header>
    <section className="papercut-hero"><div className="papercut-hero-copy"><span className="section-index">PAPERCUT / PRINT MANAGEMENT</span><img src="/brands/papercut.png" alt="PaperCut"/><h1>Utskrifter som bara<br/><strong>fungerar.</strong></h1><p>PaperCut hjälper organisationer att göra utskrifter säkrare, enklare och billigare – oavsett skrivarmärke, kontor eller arbetssätt.</p><div><a className="primary-button" href="mailto:info@selectecnordic.com?subject=Vi%20vill%20prata%20PaperCut">Prata PaperCut med oss <ArrowRight size={17}/></a><a className="text-link" href="#valj">Jämför MF och Hive <span>↓</span></a></div></div><div className="papercut-console" aria-label="Illustration av ett säkert utskriftsflöde"><div className="console-top"><span>PRINT FLOW / NORDIC HQ</span><i>LIVE</i></div><div className="console-flow"><div><Users/><b>Användare</b><small>Skickar utskrift</small></div><ArrowRight/><div className="active"><ShieldCheck/><b>PaperCut</b><small>Kontrollerar & håller</small></div><ArrowRight/><div><Printer/><b>Valfri skrivare</b><small>Släpp säkert</small></div></div><div className="console-status"><span><i/>Dokument väntar säkert</span><b>12</b></div></div></section>
    <section className="papercut-proof" data-reveal><div><strong>100 miljoner</strong><span>användare</span></div><div><strong>100 000</strong><span>organisationer</span></div><div><strong>195</strong><span>länder</span></div><p>PaperCut har utvecklat print management sedan 1998 och används från mindre verksamheter till globala organisationer.</p></section>
    <section className="papercut-benefits" id="varfor"><div className="section-intro" data-reveal><div><span className="section-index">01 / VAD NI VINNER</span><h2>Kontroll utan att göra utskriften krånglig.</h2></div><p>Användaren ska kunna skriva ut som vanligt. IT ska få säkerhet, överblick och färre problem.</p></div><div className="papercut-benefit-grid">{benefits.map(({icon:Icon,title,text},index)=><article key={title} data-reveal><Icon/><span>0{index+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="papercut-choice" id="valj"><div className="choice-heading" data-reveal><span className="section-index">02 / VÄLJ RÄTT PLATTFORM</span><h2>PaperCut MF eller<br/>PaperCut Hive?</h2><p>Båda ger säker utskrift och kontroll. Skillnaden är främst hur lösningen driftas och hur mycket den ska anpassas.</p></div><div className="papercut-choice-grid"><article data-reveal><Server/><small>SJÄLVHOSTAD / HYBRID</small><h3>PaperCut MF</h3><p>För organisationer som vill ha djup kontroll, avancerade regler och integration direkt i multifunktionsskrivaren.</p><ul><li><Check/>Stora eller komplexa miljöer</li><li><Check/>Avancerad rapportering och kostnadsstyrning</li><li><Check/>Integrerad skanning och embedded-appar</li></ul><a href="https://www.papercut.com/products/mf/" target="_blank" rel="noreferrer">Läs om PaperCut MF ↗</a></article><article data-reveal><Cloud/><small>MOLNBASERAD</small><h3>PaperCut Hive</h3><p>För organisationer som vill minska lokal infrastruktur och få modern, molnbaserad print management.</p><ul><li><Check/>Ingen traditionell printserver</li><li><Check/>Enkel utrullning för kontor och hybrida team</li><li><Check/>Säker utskrift från flera enheter</li></ul><a href="https://www.papercut.com/products/hive/" target="_blank" rel="noreferrer">Läs om PaperCut Hive ↗</a></article></div></section>
    <section className="papercut-selectec" id="selectec" data-reveal><span className="section-index">03 / SELECTEC NORDIC</span><h2>Programvaran är global.<br/>Kompetensen finns nära.</h2><p>Vi hjälper er välja rätt PaperCut-plattform, verifiera miljön, installera, konfigurera och utbilda. När lösningen är i drift finns vårt nordiska team kvar för support och vidareutveckling.</p><div><span>Analys</span><ArrowRight/><span>Design</span><ArrowRight/><span>Installation</span><ArrowRight/><span>Utbildning</span><ArrowRight/><span>Support</span></div><a className="primary-button" href="mailto:info@selectecnordic.com?subject=PaperCut%20rådgivning">Boka en första genomgång <ArrowRight size={17}/></a></section>
    <footer><a className="brand footer-brand" href="/"><img src="/selectec-nordic-logo-mono.png" alt="Selectec Nordic"/></a><p>Certifierad nordisk kompetens inom säker utskrift och dokumentflöden.</p><div><a href="/">Selectec Nordic</a><a href="https://www.papercut.com/" target="_blank" rel="noreferrer">PaperCut</a></div><small>© 2026 Selectec Nordic</small></footer>
  </main>
}
